export enum ValidatorReasonEnum {
  INVALID_FORMAT = "INVALID_FORMAT",
  FIELD_VALUE_NOT_EQUAL = "FIELD_VALUE_NOT_EQUAL",
  FIELD_VALUE_NOT_UNIQUE = "FIELD_VALUE_NOT_UNIQUE",
  FIELD_VALUE_TOO_SHORT = "FIELD_VALUE_TOO_SHORT",
  FIELD_VALUE_TOO_LONG = "FIELD_VALUE_TOO_LONG",
  FIELD_VALUE_WRONG_LENGTH = "FIELD_VALUE_WRONG_LENGTH",
  FIELD_VALUE_REQUIRED = "FIELD_VALUE_REQUIRED",
  INVALID_NUMBER_TYPE = "INVALID_NUMBER_TYPE",
  INVALID_STRING_TYPE = "INVALID_STRING_TYPE",
  INVALID_ETH_ADDRESS_TYPE = "INVALID_ETH_ADDRESS_TYPE",
  INVALID_QUERY_STRING = "INVALID_QUERY_STRING",
  INVALID_CUID_TYPE = "INVALID_CUID_TYPE",
}
