name: Server CI

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

defaults:
  run:
    working-directory: ./server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test
